import socket
import random
def power(base, exp, mod):
    return pow(base, exp, mod)
print("\nAlice")
print("\nUser Input:")
p = int(input("Prime number: "))
g = int(input("Primitive root: "))
Xa = random.randint(1,10)
print("\nChoose private key randomly:", Xa)
Ya = power(g, Xa, p)
print("Compute public key:", Ya)
cl = socket.socket()
print("\nSocket created")
print("Connecting to attacker...")
cl.connect(('127.0.0.1', 5009))
print("Connected to attacker")
cl.send(str(Ya).encode())
print("Public key sent to attacker")
Yd = int(cl.recv(1024).decode())
print("Public key from attacker:", Yd)
Ka = power(Yd, Xa, p)
print("Common key between Alice and Attacker:", Ka)
cl.close()
print("Connection closed")
