import socket
def power(base, exp, mod):
    return pow(base, exp, mod)
print("\nAttacker")
print("\nUser Input:")
p = int(input("Prime number: "))
g = int(input("Primitive root: "))
Xd1 = int(input("Private key for Alice (Xd1): "))
Xd2 = int(input("Private key for Bob (Xd2): "))
print("\nCompute public key:")
Yd1 = power(g, Xd1, p)
Yd2 = power(g, Xd2, p)
print("Public key for Alice:", Yd1)
print("Public key for Bob:", Yd2)
#  Alice 
sv = socket.socket()
print("\nSocket created")
sv.bind(('127.0.0.1', 5009))
print("Socket bound to port 5009")
sv.listen(1)
print("Listening for incoming connection from Alice...")
c1, a1 = sv.accept()
print("Connection accepted from", a1)
Ya = int(c1.recv(1024).decode())
print("Public key received from Alice:", Ya)
c1.send(str(Yd1).encode())
print("Public key sent to Alice")
Ka = power(Ya, Xd1, p)
print("Common key between Alice and Attacker:", Ka)
c1.close()
print("Connection closed with Alice")
sv.close()
# Bob
sv2 = socket.socket()
print("\nSocket created")
sv2.bind(('127.0.0.1', 5010))
print("Socket bound to port 5010")
sv2.listen(1)
print("Listening for incoming connection from Bob...")
c2, a2 = sv2.accept()
print("Connection accepted from", a2)
Yb = int(c2.recv(1024).decode())
print("Public key received from Bob:", Yb)
c2.send(str(Yd2).encode())
print("Public key sent to Bob")
Kb = power(Yb, Xd2, p)
print("Common key between Bob and Attacker:", Kb)
c2.close()
print("Connection closed with Bob")
sv2.close()
