import socket
import random
def power(base, exp, mod):
    return pow(base, exp, mod)
print("\nBob")
print("\nUser Input:")
p = int(input("Prime number: "))
g = int(input("Primitive root: "))
Xb = random.randint(1,10)
print("\nChoose private key randomly:", Xb)
Yb = power(g, Xb, p)
print("Compute public key:", Yb)
cl = socket.socket()
print("\nSocket created")
print("Connecting to attacker...")
cl.connect(('127.0.0.1', 5010))
print("Connected to attacker")
cl.send(str(Yb).encode())
print("Public key sent to attacker")
Yd = int(cl.recv(1024).decode())
print("Public key from attacker:", Yd)
Kb = power(Yd, Xb, p)
print("Common key between Bob and Attacker:", Kb)
cl.close()
print("Connection closed")
